// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package models

import ()

type Replay struct {
	ID       int64
	FilePath string
	Owner    int64
}

type User struct {
	ID   int64
	Name string
}
